INSERT INTO users (email, username, password_hash, is_verified) VALUES
('user1@hivemind.com', 'bytehunter', '$2b$10$examplehashedpassword', 1),
('user2@hivemind.com', 'neuralbee', '$2b$10$examplehashedpassword', 1),
('user3@hivemind.com', 'doomcoder', '$2b$10$examplehashedpassword', 1),
('user4@hivemind.com', 'stackpilot', '$2b$10$examplehashedpassword', 1),
('user5@hivemind.com', 'pixelstorm', '$2b$10$examplehashedpassword', 1),
('user6@hivemind.com', 'cryptomonk', '$2b$10$examplehashedpassword', 1),
('user7@hivemind.com', 'siliconfox', '$2b$10$examplehashedpassword', 1),
('user8@hivemind.com', 'darkrender', '$2b$10$examplehashedpassword', 1),
('user9@hivemind.com', 'animatrix', '$2b$10$examplehashedpassword', 1),
('user10@hivemind.com', 'quantumdev', '$2b$10$examplehashedpassword', 1),

('user11@hivemind.com', 'bugslayer', '$2b$10$examplehashedpassword', 1),
('user12@hivemind.com', 'techwanderer', '$2b$10$examplehashedpassword', 1),
('user13@hivemind.com', 'gamemancer', '$2b$10$examplehashedpassword', 1),
('user14@hivemind.com', 'retrobyte', '$2b$10$examplehashedpassword', 1),
('user15@hivemind.com', 'datasmith', '$2b$10$examplehashedpassword', 1),
('user16@hivemind.com', 'codealchemy', '$2b$10$examplehashedpassword', 1),
('user17@hivemind.com', 'framewizard', '$2b$10$examplehashedpassword', 1),
('user18@hivemind.com', 'aioracle', '$2b$10$examplehashedpassword', 1),
('user19@hivemind.com', 'devnomad', '$2b$10$examplehashedpassword', 1),
('user20@hivemind.com', 'cyberhive', '$2b$10$examplehashedpassword', 1),

('user21@hivemind.com', 'logicloom', '$2b$10$examplehashedpassword', 1),
('user22@hivemind.com', 'spacewalker', '$2b$10$examplehashedpassword', 1),
('user23@hivemind.com', 'filmbuff', '$2b$10$examplehashedpassword', 1),
('user24@hivemind.com', 'bollyfan', '$2b$10$examplehashedpassword', 1),
('user25@hivemind.com', 'horrorfreak', '$2b$10$examplehashedpassword', 1),
('user26@hivemind.com', 'fitnessmode', '$2b$10$examplehashedpassword', 1),
('user27@hivemind.com', 'musicpulse', '$2b$10$examplehashedpassword', 1),
('user28@hivemind.com', 'stockwatcher', '$2b$10$examplehashedpassword', 1),
('user29@hivemind.com', 'travelbug', '$2b$10$examplehashedpassword', 1),
('user30@hivemind.com', 'chefcraft', '$2b$10$examplehashedpassword', 1),

('user31@hivemind.com', 'memelord', '$2b$10$examplehashedpassword', 1),
('user32@hivemind.com', 'opensourcepro', '$2b$10$examplehashedpassword', 1),
('user33@hivemind.com', 'hardcorebuilder', '$2b$10$examplehashedpassword', 1),
('user34@hivemind.com', 'gpuoverlord', '$2b$10$examplehashedpassword', 1),
('user35@hivemind.com', 'kernelpanic', '$2b$10$examplehashedpassword', 1),
('user36@hivemind.com', 'aiarchitect', '$2b$10$examplehashedpassword', 1),
('user37@hivemind.com', 'webwizard', '$2b$10$examplehashedpassword', 1),
('user38@hivemind.com', 'doomslayer', '$2b$10$examplehashedpassword', 1),
('user39@hivemind.com', 'codenectar', '$2b$10$examplehashedpassword', 1),
('user40@hivemind.com', 'databeekeeper', '$2b$10$examplehashedpassword', 1),

('user41@hivemind.com', 'cloudsurfer', '$2b$10$examplehashedpassword', 1),
('user42@hivemind.com', 'mltrainer', '$2b$10$examplehashedpassword', 1),
('user43@hivemind.com', 'physicsmind', '$2b$10$examplehashedpassword', 1),
('user44@hivemind.com', 'bookwormx', '$2b$10$examplehashedpassword', 1),
('user45@hivemind.com', 'cinecritic', '$2b$10$examplehashedpassword', 1),
('user46@hivemind.com', 'astrogeek', '$2b$10$examplehashedpassword', 1),
('user47@hivemind.com', 'devhacker', '$2b$10$examplehashedpassword', 1),
('user48@hivemind.com', 'cryptoking', '$2b$10$examplehashedpassword', 1),
('user49@hivemind.com', 'pixelbee', '$2b$10$examplehashedpassword', 1),
('user50@hivemind.com', 'hivemaster', '$2b$10$examplehashedpassword', 1);